### ISSUE TITLE
Throws unicode error

### ISSUE THREAD

**Issue by kmhari** [AnuragKr/investments#1]
Traceback (most recent call last):
  File "anurag.py", line 104, in <module>
    extractInfo('https://gist.githubusercontent.com/murtuzakz/4bd887712703ff14c9b0f7c18229b332/raw/d0dd1c59016e2488dcbe0c8e710a1c5df9c3672e/season7.json')
  File "anurag.py", line 55, in extractInfo
    D_invest[inv_name].append(comp_name.replace('\xa0', ' '))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 0: ordinal not in range(128)

**Comment by AnuragKr** [comment]
Error has been Solved.
First I converted it into byte code and then decoded it.
`'
                                 if(match):
                                     encoded_str = comp_name.encode('ascii','ignore')#First converting into bytes code
                                     decoded_str = encoded_str.decode('utf-8')#Decoding bytes code
                                     D_invest[inv_name].append(decoded_str)
                                 else:
                                     D_invest[inv_name].append(comp_name)
                                 `
